typography_spectrum: 0.04210494761355221
color:
  brandStrength: 0.2950638469774276
  lightness: 0.9290463461074978
  saturation: 0.5168041179422289
  rhythmicContrast: 0.15827875956892967
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
layout_spectrum: 0.9090896998532116
name: SimplyWorks
title: Fuji Xerox
description: 'Solutions that Simply Work - for you, with you.'
